// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/ArticleVG.shared.kt
// Package: com.lightningkite.khrysaliswebsite.vg
import { ArticleXml } from '../layout/ArticleXml'
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { androidWidgetTextViewBindString } from 'khrysalis/dist/observables/binding/TextView.binding.actual'
import { ObservableStack } from 'khrysalis/dist/observables/ObservableStack.shared'
import { ConstantObservableProperty } from 'khrysalis/dist/observables/ConstantObservableProperty.shared'

//! Declares com.lightningkite.khrysaliswebsite.vg.ArticleVG
export class ArticleVG extends ViewGenerator {
    public readonly stack: ObservableStack<ViewGenerator>;
    public constructor(stack: ObservableStack<ViewGenerator>) {
        super();
        this.stack = stack;
    }
    
    
    
    //! Declares com.lightningkite.khrysaliswebsite.vg.ArticleVG.title
    public get title(): string { return "Article"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new ArticleXml();
        
        const view = xml.setup(dependency);
        
        
        //--- Set Up xml.question (overwritten on flow generation)
        androidWidgetTextViewBindString(xml.question, new ConstantObservableProperty("This is my really long and wandering question please help?"));
        
        //--- Set Up xml.content (overwritten on flow generation)
        
        //--- Generate End (overwritten on flow generation)
        
        return view;
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    
    //--- Body End
}

