// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/HomeVG.shared.kt
// Package: com.lightningkite.khrysaliswebsite.vg
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { HomeXml } from '../layout/HomeXml'

//! Declares com.lightningkite.khrysaliswebsite.vg.HomeVG
export class HomeVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    
    
    //! Declares com.lightningkite.khrysaliswebsite.vg.HomeVG.title
    public get title(): string { return "Home"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new HomeXml();
        
        const view = xml.setup(dependency);
        
        
        //--- Set Up xml.featureList (overwritten on flow generation)
        
        //--- Set Up xml.tutorial (overwritten on flow generation)
        xml.tutorial.onclick = (_ev) => { _ev.stopPropagation(); 
            this.tutorialClick();
        };
        
        //--- Set Up xml.docs (overwritten on flow generation)
        xml.docs.onclick = (_ev) => { _ev.stopPropagation(); 
            this.docsClick();
        };
        
        //--- Generate End (overwritten on flow generation)
        
        return view;
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    public tutorialClick(): void {
    }
    public docsClick(): void {
    }
    
    //--- Body End
}

