// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: vg/SetupVG.shared.kt
// Package: com.lightningkite.khrysaliswebsite.vg
import { ViewGenerator } from 'khrysalis/dist/views/ViewGenerator.shared'
import { SetupXml } from '../layout/SetupXml'

//! Declares com.lightningkite.khrysaliswebsite.vg.SetupVG
export class SetupVG extends ViewGenerator {
    public constructor() {
        super();
    }
    
    
    
    //! Declares com.lightningkite.khrysaliswebsite.vg.SetupVG.title
    public get title(): string { return "Setup"; }
    
    
    public generate(dependency: Window): HTMLElement {
        const xml = new SetupXml();
        
        const view = xml.setup(dependency);
        
        
        //--- Generate End (overwritten on flow generation)
        
        return view;
    }
    
    //--- Init
    
    
    
    //--- Actions
    
    
    //--- Body End
}

