// Generated by Khrysalis TypeScript converter - this file will be overwritten.
// File: HasSourceLink.shared.kt
// Package: com.lightningkite.khrysaliswebsite

//! Declares com.lightningkite.khrysaliswebsite.HasSourceLink
export interface HasSourceLink {
    
    readonly sourceLink: string;
    
}

